<?php

namespace OnyxERP\Core\Domain\ValueObject;

use \PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-28 at 09:49:40.
 */
class PfCodTest extends TestCase
{

    /**
     * @var PfCod
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function testConstructorWithSuccess()
    {
        $pfCod = 1;
        $this->object = new PfCod($pfCod);
        $this->assertInternalType('integer', $this->object->getValue());
        $this->assertEquals($pfCod, $this->object->getValue());
    }
    /**
     * @expectedException InvalidArgumentException
     */
    public function testConstructorWithoutSuccess()
    {
        $pfCod = '';
        $this->object = new PfCod($pfCod);
    }
}
