<?php

namespace OnyxERP\Core\Domain\ValueObject;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-28 at 09:49:40.
 */
class PfCodTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var PfCod
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function testConstructor()
    {
        $pfCod = 1;
        $this->object = new PfCod($pfCod);
        $this->assertTrue(is_int($this->object));
        $this->assertEquals($pfCod, $this->object->getValue());
    }

}
