<?php

namespace OnyxERP\Core\Application\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-19 at 09:32:08.
 */
class ServiceAbstractTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ServiceAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $app = require __DIR__ . DIRECTORY_SEPARATOR .'..' . DIRECTORY_SEPARATOR .'..' .DIRECTORY_SEPARATOR .'..'.DIRECTORY_SEPARATOR .'..'.DIRECTORY_SEPARATOR.'bootstrap.php';
        $this->object = new ServiceAbstract($app);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
    /**
     * @covers OnyxERP\Core\Application\Service\ServiceAbstract::__construct
     */
    public function testConstructor()
    {
        $app = require __DIR__ . DIRECTORY_SEPARATOR .'..' . DIRECTORY_SEPARATOR .'..' .DIRECTORY_SEPARATOR .'..'.DIRECTORY_SEPARATOR .'..'.DIRECTORY_SEPARATOR.'bootstrap.php';
        $this->object = new ServiceAbstract($app);
    }
    /**
     * @covers OnyxERP\Core\Application\Service\ServiceAbstract::getApp
     */
    public function testGetApp()
    {
        $app = $this->object->getApp();
        $this->assertInstanceOf('\Silex\Application', $app);
    }

    /**
     * @covers OnyxERP\Core\Application\Service\ServiceAbstract::getUsuarioCod
     */
    public function testGetUsuarioCod()
    {
        $usuarioCod = $this->object->getUsuarioCod();
        $this->assertEquals(0, $usuarioCod);
    }

}
