<?php

namespace OnyxERP\Core\Application\Service;

use \PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-28 at 09:00:17.
 */
class AboutServiceTest extends TestCase
{

    /**
     * @var AboutService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        chdir(__DIR__);
        $app = require '../../../../../bootstrap.php';
        $this->object = new AboutService($app);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers OnyxERP\Core\Application\Service\AboutService::getDadosApp
     * @todo   Implement testGetDadosApp().
     */
    public function testGetDadosApp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
