<?php

namespace OnyxERP\Core\Application\Service;

use \OnyxERP\Core\Domain\ValueObject\PfCod;
use \PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-28 at 09:00:42.
 */
class BiometriaServiceTest extends TestCase
{

    /**
     * @var BiometriaService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        chdir(__DIR__);
        $app = require '../../../../../bootstrap.php';
        $this->object = new BiometriaService($app);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers OnyxERP\Core\Application\Service\BiometriaService::getDadosBiometria
     */
    public function testGetDadosBiometria()
    {
        $pfCod = rand(1,1200);
        $voPfCod = new PfCod($pfCod);
        $lista = $this->object->getDadosBiometria($voPfCod);
        $this->assertTrue(is_array($lista));
    }
    
}
