<?php

namespace OnyxERP\Core\Application\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-28 at 11:54:50.
 */
class DriveServiceTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var DriveService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        chdir(__DIR__);
        $app = require '../../../../../bootstrap.php';
        $this->object = new DriveService($app);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}
