<?php

namespace OnyxERP\Core\Application\Service;

use \OnyxERP\Core\Domain\ValueObject\PfCod;
use \PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-28 at 11:54:50.
 */
class DriveServiceTest extends TestCase
{

    /**
     * @var DriveService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        chdir(__DIR__);
        $app = include '../../../../../bootstrap.php';
        $this->object = new DriveService($app);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function testGetDadosDigitalizacao()
    {
        $pfCod = rand(1, 1200);
        $voPfCod = new PfCod($pfCod);
        $lista = $this->object->getDadosDigitalizacao($voPfCod);
        $this->assertTrue(is_array($lista));
    }

}
