<?php

namespace OnyxERP\Core\Application\Service;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-25 at 01:24:16.
 */
class JSONServiceProviderTest extends TestCase
{

    /**
     * @var JSONServiceProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        chdir(__DIR__);
        $app = include '../../../../../bootstrap.php';
        $this->object = new JSONServiceProvider($app);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    /**
     * @covers OnyxERP\Core\Application\Service\JSONServiceProvider::boot
     */
    public function testBoot()
    {
        $this->markTestSkipped();
    }

    /**
     * @covers OnyxERP\Core\Application\Service\JSONServiceProvider::register
     */
    public function testRegister()
    {
        $this->markTestSkipped();
    }

    /**
     * @covers OnyxERP\Core\Application\Service\JSONServiceProvider::createJSON
     */
    public function testCreateJSON()
    {
        $fileId = 'teste.json';
        $parameters = ['status' => true, 'data' => ['status' => true]];
        $this->object->createJSON($parameters, $fileId);
        $this->assertTrue(file_exists($fileId));
    }

    /**
     * @covers OnyxERP\Core\Application\Service\JSONServiceProvider::readJsonToArray
     * @todo   Implement testReadJsonToArray().
     */
    public function testReadJsonToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OnyxERP\Core\Application\Service\JSONServiceProvider::checkDelayByBuildJSON
     * @todo   Implement testCheckDelayByBuildJSON().
     */
    public function testCheckDelayByBuildJSON()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
