<?php

namespace OnyxERP\Core\Application\Service\JwtAPI;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-31 at 16:08:17.
 */
class CheckJWTTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var CheckJWT
     */
    protected $object;
    
    protected  $jwt;
    
    protected $app;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        chdir(__DIR__);
        $this->app = include '../../../../../../bootstrap.php';

        $dados = [
            "apiKey" => "NTdjOTc0ZjM3YzRmOA==",
            "app" => [
                "id" => "99",
                "apikey" => "57c974f37c4f8",
                "name" => "Dash"
            ]
        ];
        $encode = new Encode($this->app, $dados);
        $this->jwt = $encode->getResponse();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->jwt = null;
        $this->object = null;
    }
    
    /**
     * @covers OnyxERP\Core\Application\Service\JwtAPI\CheckJWT::getResponse
     * @expectedException Exception
     */
    public function testCheckJWTWithoutSuccess()
    {
        $this->object = new CheckJWT($this->app, '');
        $this->object->getResponse();
    }
    
    /**
     * @covers OnyxERP\Core\Application\Service\JwtAPI\CheckJWT::getResponse
     */
    public function testCheckJWTWithSuccess()
    {        
        $this->object = new CheckJWT($this->app, $this->jwt);
        $condition = $this->object->getResponse();
        $this->assertTrue($condition);
    }

}
