<?php

namespace OnyxERP\Core\Application\Service\JwtAPI;

use \Exception;
use \OnyxERP\Core\Application\Service\JwtAPI\Encode;
use \PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-29 at 14:14:37.
 */
class DecodeTest extends TestCase
{

    /**
     * @var Decode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        chdir(__DIR__);
        $app = include '../../../../../../bootstrap.php';
        
        $dados = [
            "apiKey" => "NTdjOTc0ZjM3YzRmOA==",
            "app" => [
                "id" => "99",
                "apikey" => "57c974f37c4f8",
                "name" => "Dash"
            ]
        ];
        $encode = new Encode($app, $dados);
        $jwt = $encode->getResponse();
        $this->object = new Decode($app, $jwt);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    /**
     * @covers OnyxERP\Core\Application\Service\JwtAPI\Decode::__construct
     */
    public function testDecodeWithSuccess()
    {
        $response = $this->object->getResponse();
        $this->assertInternalType('array', $response);
    }
    /**
     * @covers OnyxERP\Core\Application\Service\JwtAPI\Decode::__construct
     * @expectedException Exception
     */
    public function testDecodeWithoutSuccess()
    {
        chdir(__DIR__);
        $app = include '../../../../../../bootstrap.php';
        
        $this->object = new Decode($app, null);
    }
}
