<?php

namespace OnyxERP\Core\Application\Service\JwtAPI;

use \PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-29 at 09:14:18.
 */
class EncodeTest extends TestCase
{

    /**
     * @var Encode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        chdir(__DIR__);
        $app = include '../../../../../../bootstrap.php';
        $dados = [
            "apiKey" => "NTdjOTc0ZjM3YzRmOA==",
            "app" => [
                "id" => "99",
                "apikey" => "57c974f37c4f8",
                "name" => "Dash"
            ]
        ];
        $this->object = new Encode($app, $dados);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }
    /**
     * 
     */
    public function testConstructorWithSuccess()
    {
        chdir(__DIR__);
        $app = include '../../../../../../bootstrap.php';
        $dados = [
            "apiKey" => "NTdjOTc0ZjM3YzRmOA==",
            "app" => [
                "id" => "99",
                "apikey" => "57c974f37c4f8",
                "name" => "Dash"
            ]
        ];
        $encode = new Encode($app, $dados);
        $this->assertInstanceOf(Encode::class, $encode);
        $this->assertInternalType('string', $encode->getResponse());
    }
    /**
     * @expectedException Exception
     */
    public function testConstructorWithoutSuccess()
    {
        chdir(__DIR__);
        $app = include '../../../../../../bootstrap.php';
        $dados = [
            
        ];
        $encode = new Encode($app, $dados);
        $this->assertInstanceOf(Encode::class, $encode);
        $this->assertInternalType('string', $encode->getResponse());
    }
}
