<?php

namespace OnyxERP\Core\Application\Service\JwtAPI;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-29 at 09:14:18.
 */
class EncodeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Encode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Encode;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}
