<?php

namespace OnyxERP\Core\Application\Service\JwtAPI;

use \PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-29 at 09:14:18.
 */
class EncodeTest extends TestCase
{

    /**
     * @var Encode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        chdir(__DIR__);
//        $app = include '../../../../../../bootstrap.php';
//        $this->object = new Encode($app, []);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testConstructor()
    {
        $classname = 'Encode';

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
                ->disableOriginalConstructor()
                ->getMock();
        
        $app = include '../../../../../../bootstrap.php';
        $dados = ['app'=>['apikey' => '1345ddda']];
        
        $mock->method('__construct')
                ->willReturn('foo');
        
        $this->assertEquals('foo', $mock->__construct($app, $dados));
    }

}
