<?php

namespace OnyxERP\Core\Application\Service\JwtAPI;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-31 at 14:03:05.
 */
class PushTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Push
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Push;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}
